import os
import re
from datetime import datetime
from typing import List

import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.utils import get_column_letter

import config
from models.email_draft import EmailDraft
from utils.logger import get_logger

log = get_logger("draft_writer")

PUROLATOR_PURPLE = "4B0082"

COLUMNS = [
    ("Company", 28),
    ("Contact", 22),
    ("Title", 24),
    ("Email", 30),
    ("Phone", 16),
    ("Mode", 18),
    ("Subject", 44),
    ("Status", 12),
    ("Generated By", 14),
    ("Date", 12),
]


def _safe_slug(*parts: str) -> str:
    raw = "_".join(p for p in parts if p) or "lead"
    slug = re.sub(r"[^A-Za-z0-9]+", "_", raw).strip("_")
    return slug[:60] or "lead"


def _write_markdown(draft: EmailDraft, out_dir: str, index: int) -> str:
    fname = f"{index:02d}_{draft.mode}_{_safe_slug(draft.company_name, draft.to_name)}.md"
    path = os.path.join(out_dir, fname)

    to_line = draft.to_email or "(no email on file — phone/LinkedIn only)"
    lines = [
        f"# {draft.company_name} — {draft.mode}",
        "",
        f"**To:** {draft.to_name} <{to_line}>",
    ]
    if draft.cc:
        lines.append(f"**Cc:** {draft.cc}")
    lines += [
        f"**Subject:** {draft.subject}",
        f"_Generated by: {draft.generated_by} · {draft.date_generated}_",
        "",
        "---",
        "",
        draft.body,
    ]
    if not draft.has_email:
        lines += ["", "---", "",
                  "> ⚠️ No email address on file for this contact. Use this copy on the "
                  "phone or once you obtain an address."]
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    return path


def _write_index(drafts: List[EmailDraft], out_dir: str, mode_name: str) -> str:
    now = datetime.now()
    filename = f"purolator_outreach_{mode_name.upper()}_{now.strftime('%Y%m%d_%H%M')}.xlsx"
    filepath = os.path.join(out_dir, filename)

    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Drafts"
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = f"A1:{get_column_letter(len(COLUMNS))}1"

    header_font = Font(name="Calibri", bold=True, color="FFFFFF", size=11)
    header_fill = PatternFill(fill_type="solid", fgColor=PUROLATOR_PURPLE)
    header_align = Alignment(horizontal="center", vertical="center", wrap_text=True)
    for col_idx, (name, width) in enumerate(COLUMNS, start=1):
        cell = ws.cell(row=1, column=col_idx, value=name)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = header_align
        ws.column_dimensions[get_column_letter(col_idx)].width = width
    ws.row_dimensions[1].height = 24

    for row_idx, d in enumerate(drafts, start=2):
        values = [d.company_name, d.to_name, "", d.to_email or "—", "",
                  d.mode, d.subject, d.status, d.generated_by, d.date_generated]
        for col_idx, value in enumerate(values, start=1):
            ws.cell(row=row_idx, column=col_idx, value=value)

    wb.save(filepath)
    return filepath


def write_drafts(drafts: List[EmailDraft], mode_name: str) -> dict:
    """Write each draft as a .md file plus a Purolator-styled .xlsx tracking
    index. Returns {"index": <xlsx path>, "drafts": [<md paths>]}."""
    os.makedirs(config.OUTPUT_DIR, exist_ok=True)
    md_paths = [_write_markdown(d, config.OUTPUT_DIR, i)
                for i, d in enumerate(drafts, start=1)]
    index_path = _write_index(drafts, config.OUTPUT_DIR, mode_name)
    log.info("Wrote %d draft files + index %s", len(md_paths), index_path)
    return {"index": index_path, "drafts": md_paths}
